databases:
  - name: foodely-db
    databaseName: foodely_db
    user: foodely-api
    region: oregon

services:
  - type: web
    name: foodely-api
    env: ruby
    region: oregon
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foodely-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
